eval(fs.readFileSync("/Users/iceselkie/bin/utils2.js")+"");
i = await (() => new Promise((resolve, reject) => require('https').get({ hostname: 'adventofcode.com', path: '/2024/day/13/input', headers: { 'User-Agent': 'Human/1.0; NodeJS-Repl/v20.10.0; Darwin/15.2', 'Connection': 'keep-alive', 'Cookie': `session=${process.env.SESSION}`, 'Priority': 'u=0, i', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache' } }, res => { let data = ''; res.on('data', chunk => data += chunk); res.on('end', () => resolve(data.trim())); }).on('error', reject)))();
i = await (() => new Promise((resolve, reject) => require('https').get({ hostname: 'adventofcode.com', path: '/2024/day/13/input', headers: { 'User-Agent': 'Human/1.0; NodeJS-Repl/v20.10.0; Darwin/15.2', 'Connection': 'keep-alive', 'Cookie': `session=${process.env.SESSION}`, 'Priority': 'u=0, i', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache' } }, res => { let data = ''; res.on('data', chunk => data += chunk); res.on('end', () => resolve(data.trim())); }).on('error', reject)))();

i = await (() => new Promise((resolve, reject) => require('https').get({ hostname: 'adventofcode.com', path: '/2024/day/13/input', headers: { 'User-Agent': 'Human/1.0; NodeJS-Repl/v20.10.0; Darwin/15.2', 'Connection': 'keep-alive', 'Cookie': `session=${process.env.SESSION}`, 'Priority': 'u=0, i', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache' } }, res => { let data = ''; res.on('data', chunk => data += chunk); res.on('end', () => resolve(data.trim())); }).on('error', reject)))();
i.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()])
ex = "Button A: X+94, Y+34\nButton B: X+22, Y+67\nPrize: X=8400, Y=5400\n\nButton A: X+26, Y+66\nButton B: X+67, Y+21\nPrize: X=12748, Y=12176\n\nButton A: X+17, Y+86\nButton B: X+84, Y+37\nPrize: X=7870, Y=6450\n\nButton A: X+69, Y+23\nButton B: X+27, Y+71\nPrize: X=18641, Y=10279"
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()].T)
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()].T).map(([l,r])=>)
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()].T).map(([l,r])=>max([min(l.slice(0,2)/l[2],min(r.slice(0,2))/r[2]]),min([max(l.slice(0,2))/l[2],max(r.slice(0,2))/r[2]])))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()].T).map(([l,r])=>max([min(l.slice(0,2)/l[2],min(r.slice(0,2))/r[2]]),min([max(l.slice(0,2))/l[2],max(r.slice(0,2))/r[2]]))))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()].T).map(([l,r])=>max([min(l.slice(0,2)/l[2],min(r.slice(0,2))/r[2]]),min([max(l.slice(0,2))/l[2],max(r.slice(0,2))/r[2]])))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()].T).map(([l,r])=>[l,r,max([min(l.slice(0,2)/l[2],min(r.slice(0,2))/r[2]]),min([max(l.slice(0,2))/l[2],max(r.slice(0,2))/r[2]]))])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,[...a,...b].min()/c.max()])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,c.min()/[...a,...b].max(),c.max()/[...a,...b].min()])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.max(c.max()/[...a,...b].min())])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).filter(i=>vdiv(vsub(c,vmul(a,i)),b).map(a=>a%1)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,i)),b).map(a=>a%1)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,i)),b).map(a=>a)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,i)),b)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,[i,i])),b)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,[i,i])),b).map(a=>a%1)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,[i,i])),b).map(a=>a%1===0)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,[i,i])),b).map(a=>a%1===0).prod()))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,[i,i])),b).map(a=>a%1===0).prod()).sum())
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(l,h+1).map(i=>vdiv(vsub(c,vmul(a,[i,i])),b).map(a=>a%1===0).prod()).sum()])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>vdiv(vsub(c,vmul(a,[i,i])),b).map(a=>a%1===0).prod()).sum()])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).filter(i=>vdiv(vsub(c,vmul(a,[i,i])),b).map(a=>a%1===0).prod())])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).filter(i=>vdiv(vsub(c,vmul(a,[i,i])),b).map(a=>a%1===0).prod()).map(i=>i)])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>vdiv(vsub(c,vmul(a,[i,i])),b))])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)])])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)])]).flat()
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)])]).flat(2)
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1])]).flat(2)
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0)]).flat(2)
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1]])]).flat(2)
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1]])])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1]])]).flat()
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).flat()
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2]).map(a=>a.min(([a,b])=>3*a+b))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2]).map(a=>a.min(([a,b])=>3*a+b))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2]).filter(a=>a.length).map(a=>a.min(([a,b])=>3*a+b))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2]).filter(a=>a.length).map(a=>a.min(([a,b])=>3*a+b,true))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2]).filter(a=>a.length).map(a=>a.min(([a,b])=>3*a+b,true)).sum()
i.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2]).filter(a=>a.length).map(a=>a.min(([a,b])=>3*a+b,true)).sum()
10000000000000
10000000000000-1e13
part 1
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2]).filter(a=>a.length).map(a=>a.min(([a,b])=>3*a+b,true))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2])
1e13-1
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()]).map(([a,b,c])=>[a,b,c,Math.floor(c.min()/[...a,...b].max()),Math.ceil(c.max()/[...a,...b].min())]).map(([a,b,c,l,h])=>[l,h,range(0,h+1).map(i=>[i,vdiv(vsub(c,vmul(a,[i,i])),b)]).filter(a=>a[1][0]==a[1][1]&&a[1][0]%1==0).map(a=>[a[0],a[1][0]])]).map(a=>a[2])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums()])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)])
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T)
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T.map(([a,b,c])=>c%gcd(a,b)))
i.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T.map(([a,b,c])=>c%gcd(a,b)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T.map(([a,b,c])=>c%gcd(a,b)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).filter(a=>a.find(([a,b,c])=>c%gcd(a,b)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).filter(a=>a.find(([a,b,c])=>!c%gcd(a,b)))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).filter(a=>a.find(([a,b,c])=>c%gcd(a,b)!==0))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).filter(a=>a.find(([a,b,c])=>(c%gcd(a,b))!==0))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).map(a=>a.find(([a,b,c])=>(c%gcd(a,b))!==0))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).map(a=>a.find(([a,b,c])=>(c%gcd(a,b))0==0))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).map(a=>a.find(([a,b,c])=>(c%gcd(a,b))===0))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).filter(a=>!a.find(([a,b,c])=>(c%gcd(a,b))!==0))
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).filter(a=>!a.find(([a,b,c])=>(c%gcd(a,b))!==0)).map(a=>a.map(([a,b,c])=>[a,b,c].map(d=>d/gcd(a,b))))
gcd
euc=(a,b)=>{let res=a>b?[a,b]:[b,a]; while(res.last!==0)res.push(res[res.length-2]%res.last);return res}
euc(87,64)
(euc2=(a,b)=>{let res=a>b?[a,b]:[b,a]; while(res.last!==0)res.push(res[res.length-2]%res.last);return res})(87,-64,3)
(euc2=(a,b)=>{let res=a>b?[a,b]:[b,a]; while(res.last!==0)res.push(res[res.length-2]%res.last);return res})(87,64,3)
(euc2=(a,b)=>{let res=euc(a,b); return res})(87,64,3)
(euc2=(a,b,c)=>{let arr=euc(a,b);let res=[[0,1]];while(euc.length>2){res.push([res.last[1]-res.last[0]*((arr[arr.length-3]-arr.last)/arr[arr.length-2]),res.last[0])} return res})(87,64,3)
(euc2=(a,b,c)=>{let arr=euc(a,b);let res=[[0,1]];while(euc.length>2){res.push([res.last[1]-res.last[0]*((arr[arr.length-3]-arr.last)/arr[arr.length-2]),res.last[0]])} return res})(87,64,3)
(euc2=(a,b,c)=>{let arr=euc(a,b);let res=[[0,1]];while(arr.length>2){res.push([res.last[1]-res.last[0]*((arr[arr.length-3]-arr.last)/arr[arr.length-2]),res.last[0]]);arr.pop()} return res})(87,64,3)
34*87+-25*64
34*64-25*87
(euc2=(a,b,c)=>{let arr=euc(a,b);let res=[[0,1]];while(arr.length>2){res.push([res.last[1]-res.last[0]*((arr[arr.length-3]-arr.last)/arr[arr.length-2]),res.last[0]]);arr.pop()} return res.last.reverse().map(a=>a*c)})(87,64,3)
87*-75+102*64
ex.s`\n\n`.map(a=>a.split("\n")).map(([a,b,c])=>[a.nums(),b.nums(),c.nums().map(a=>1e13+a)].T).filter(a=>!a.find(([a,b,c])=>(c%gcd(a,b))!==0)).map(a=>a.map(([a,b,c])=>[a,b,c].map(d=>d/gcd(a,b))))
euc2(47,11,5000000004200)
euc2(34, 67, 10000000005400)
euc2(26, 67, 10000000012748)
euc2(22, 7, 3333333337392)
ex
euc2(94,22,8400)
euc2(34,67,5400)
8400/gcd(94,22)
euc2(47,11,4200)
5400/gcd(34,67)
euc2(47,11,4200)
euc2(34,67,5400)
euc3hh=(ax,mxa,ay,mya,bx,mxb,by,myb)=>(bx-by+((mxb*(ay-ax))/mxa))/(myb-mxb*(mya/mxa))
euc3hh(16800,11,-71400,-47,-5400,67,10800,-34)